Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/10/2021
Var
// Seção de Declarações das variáveis 
    num1: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreva ( "Escreva um numero:" )
    leia (num1)
    se (num1 > 50 )entao
      escreval ( "Você digitou um número maior que cinquenta" )
    senao
      escreval( "Você digitou um número menor que cinquenta" )
    fimse
    

Fimalgoritmo