Algoritmo "semnome"

Var
// Seção de Declarações das variáveis 
  i : inteiro
  j : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    i <- 1
      enquanto i <=10 faca      // O enquanto testa antes
         escreva (i:3)
         i <- i+1
      fimenquanto
      
   escreval ("")     // O enquanto testa depois
   j <-1
   repita
      escreva (j:3)
      j <- j+1
   ate j >10


Fimalgoritmo