Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/10/2021
Var
// Seção de Declarações das variáveis 

   estacao : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva ("Digite uma estação do ano: ")
 leia(estacao)
 escolha estacao
   caso "verão"
      escreval("Use e abuse do protetor solar")
   caso "inverno"
      escreval("Lembre-se de sua mãezinha, leve o casaco")
   caso "primavera"
      escreval("É época de abusar das flores, se é que me entende")
   caso "outono"
      escreval("Outono chegou e ainda não sei porquê gosto tanto desse periodo")
   outrocaso
      escreval(" A estrutura é essa, mas não esta funcionando")
fimescolha

Fimalgoritmo