Algoritmo "função escolha"
Var
   estacao: caractere


Inicio
   escreva ("Digite uma  estação do ano: ")
   leia (estacao)
   escolha estacao
      caso "verao"
         escreval ( "Passe Protetor"  )
      caso "inverno"
         escreval ( "Agasalha-se"   )
      caso "primavera"
         escreval ( "Aprecie a vida verde"   )
      caso "outono"
         escreval("Hora da colheita"  )
      outrocaso
         escreval("Digite uma estação válida")
fimescolha

Fimalgoritmo